<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-TTL6LUL" ignored="0" name="InsertSalary" tests="11" failures="6" timestamp="2021-03-02T21:45:26 ICT" time="1.482" errors="0">
  <testcase name="insertSalary" time="0.192" classname="UnitTest.SalaryDAOTest"/>
  <testcase name="insertSalary1" time="0.112" classname="UnitTest.SalaryDAOTest"/>
  <testcase name="insertSalary10" time="0.078" classname="UnitTest.SalaryDAOTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at UnitTest.SalaryDAOTest.insertSalary10(SalaryDAOTest.java:213)
at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:172)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- insertSalary10 -->
  <testcase name="insertSalary2" time="0.058" classname="UnitTest.SalaryDAOTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at UnitTest.SalaryDAOTest.insertSalary2(SalaryDAOTest.java:93)
at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:172)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- insertSalary2 -->
  <testcase name="insertSalary3" time="0.045" classname="UnitTest.SalaryDAOTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at UnitTest.SalaryDAOTest.insertSalary3(SalaryDAOTest.java:108)
at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:172)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- insertSalary3 -->
  <testcase name="insertSalary4" time="0.035" classname="UnitTest.SalaryDAOTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at UnitTest.SalaryDAOTest.insertSalary4(SalaryDAOTest.java:123)
at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:172)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- insertSalary4 -->
  <testcase name="insertSalary5" time="0.162" classname="UnitTest.SalaryDAOTest"/>
  <testcase name="insertSalary6" time="0.033" classname="UnitTest.SalaryDAOTest"/>
  <testcase name="insertSalary7" time="0.031" classname="UnitTest.SalaryDAOTest"/>
  <testcase name="insertSalary8" time="0.054" classname="UnitTest.SalaryDAOTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at UnitTest.SalaryDAOTest.insertSalary8(SalaryDAOTest.java:183)
at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:172)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- insertSalary8 -->
  <testcase name="insertSalary9" time="0.028" classname="UnitTest.SalaryDAOTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at UnitTest.SalaryDAOTest.insertSalary9(SalaryDAOTest.java:198)
at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:172)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- insertSalary9 -->
</testsuite> <!-- InsertSalary -->
